name: 'Setup the repository and Go'

author: 'OpenTelemetry Authors'

description: 'Checks out the repository and sets up a Go environment for use in actions by'

inputs:
  setup-go-version:
    description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.'
    default: ~1.21.5

  setup-go-cache:
    description: Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    default: false

  cache-go-modules:
    description: Used to specify whether custom caching is needed. Set to false, if you'd like to disable custom caching.
    default: true

outputs:
  cache-go-modules-hit:
    description: 'Whether the custom caching was hit or not.'
    value: ${{ steps.cache-go-modules.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: ${{ inputs.setup-go-version }}
        cache: ${{ inputs.setup-go-cache }}

    - name: Cache Go modules
      id: cache-go-modules
      if: ${{ inputs.cache-go-modules }}
      uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      env:
        cache-name: cache-go-modules
      with:
        path: |
          ~\go\pkg\mod
          ~\AppData\Local\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
