name: build-and-test-windows
on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows-unittest:
    runs-on: windows-latest
    steps:
      - name: Setup repo and Go
        uses: ./github/actions/setup-repo-and-go

      - name: Run Unit Tests
        run: make gotest

  windows-service-test:
    runs-on: windows-latest
    steps:
      - name: Setup repo and Go
        uses: ./github/actions/setup-repo-and-go

      - name: Make otelcorecol
        run: make otelcorecol

      - name: Install otelcorecol as a service
        run: |
          New-Service -Name "otelcorecol" -BinaryPathName "${PWD}\bin\otelcorecol_windows_amd64 --config ${PWD}\examples\local\otel-config.yaml"
          eventcreate.exe /t information /id 1 /l application /d "Creating event provider for 'otelcorecol'" /so otelcorecol

      - name: Test otelcorecol service
        run: |
          (Start-Service otelcorecol -PassThru).WaitForStatus('Running', '00:00:30')
          (Stop-Service otelcorecol -PassThru).WaitForStatus('Stopped', '00:00:30')

      - name: Remove otelcorecol service
        run: |
          Remove-Service otelcorecol
          Remove-Item HKLM:\SYSTEM\CurrentControlSet\Services\EventLog\Application\otelcorecol
